# Generated by Django 5.1.1 on 2024-09-06 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0002_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], default='IN', max_length=3)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='propietarios.propietario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='propietarios.vehiculo')),
            ],
        ),
    ]
